name: build

on:
  pull_request:
    types: [opened, synchronize]
  merge_group:
    types: [checks_requested]
  push:
    # Always run on push to main. The build cache can only be reused
    # if it was saved by a run from the repository's default branch.
    # The run result will be identical to that from the merge queue
    # because the commit is identical, yet we need to perform it to
    # seed the build cache.
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  HATCH_VERSION: 1.7.0

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          cache: 'pip'
          cache-dependency-path: '**/pyproject.toml'
          python-version: '3.10'

      - name: Install hatch
        run: pip install hatch==$HATCH_VERSION

      - name: Run unit tests
        run: hatch run unit:test

      - name: Publish test coverage
        uses: codecov/codecov-action@v1

  integration:
    if: github.event_name == 'pull_request'
    environment: account-admin
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: "${{ secrets.DATABRICKS_HOST }}"
      ARM_TENANT_ID: "${{ secrets.ARM_TENANT_ID }}"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.5.0


      - name: Install Python
        uses: actions/setup-python@v4
        with:
          cache: 'pip'
          cache-dependency-path: '**/pyproject.toml'
          python-version: '3.10'

      - run: pip install databricks-sdk==0.10.0
      - run: python src/databricks/labs/ucx/mixins/oidc.py

      - uses: databricks/setup-cli@main

      # For now, Databricks SDK cannot pickup the OIDC Federated Credential, but we can get the ID token the similar way as @actions/core and send it as client_credential
      # https://github.com/actions/toolkit/blob/0d638344746a652dedde8baa2ac04a10e0e0a53d/packages/core/src/oidc-utils.ts
      # https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow#third-case-access-token-request-with-a-federated-credential
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - run: echo "${{ vars.TEST_SOMETHING }} is there! $ACTIONS_ID_TOKEN_REQUEST_URL is the url"

      - run: databricks clusters list

      - name: 'Run Azure CLI commands'
        run: az account show

  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          cache: 'pip'
          cache-dependency-path: '**/pyproject.toml'
          python-version: 3.10.x

      - name: Install hatch
        run: pip install hatch==$HATCH_VERSION

      - name: Verify linting
        run: hatch run lint:verify
